### PR TITLE
Fix for HepMC vertex issue (fixes #1013)

### LINKED ISSUE #1013: Final state particles in HepMC are forced to vertex 0,0,0
We are trying to originate particles from a specific vertex (for background studies). Since HepMC needs an incoming particle in every vertex, we set this minimal test up like so:

g (13)    g(1)
----> v --->

All particles are gammas, the number in parentheses is their status. 13 is arbitrary to signify "virtual", anything above 10 is ok for HepMC. v is at (30,0,100,100). In the example below I add a second out-going gamma with status 13 to demonstrate that it has the correct vertex.

 - OS version: Some debian flavor (I'm running in a container)
 - Compiler version: GCC 12.2.0
 - Package version: latest commit in git log is 665d9defdddba9fc4a66b613bdcae42a2eea9d77
 - Reproduced by: 
```
cmake -S DD4hep -B DD4hep/build -DDD4HEP_USE_GEANT4=ON -DDD4HEP_USE_EDM4HEP=ON -DDD4HEP_USE_HEPMC3=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DROOT_DIR=/usr/local -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=DD4hep/install

make install
```

Make an input file
```
cat <<EOF > small.hepmc
HepMC::Version 3.02.00
HepMC::Asciiv3-START_EVENT_LISTING
E 1 1 3
U GEV MM
P 1 0 22 1.4367394278317271e+00 0.0000000000000000e+00 4.7891314261057571e+00 5.0000000000000000e+00 0.0000000000000000e+00 13
V -1 0 [1] @ 3.0000000000000000e+01 0.0000000000000000e+00 1.0000000000000000e+02 1.0000000000000000e+02
P 2 -1 22 5.0000000000000000e+00 0.0000000000000000e+00 0.0000000000000000e+00 5.0000000000000000e+00 0.0000000000000000e+00 1
P 3 -1 22 10.0000000000000000e+00 0.0000000000000000e+00 0.0000000000000000e+00 10.0000000000000000e+00 0.0000000000000000e+00 13
EOF
```

Then run with
```
ddsim --compactFile ./DD4hep/install/DDDetectors/compact/SiD.xml --numberOfEvents 1 --inputFiles small.hepmc --outputFile small.edm4hep.root
```

Result:
```
root -l small.edm4hep.root
events->Show(0)
[...]
 MCParticles.PDG = 22, 22, 22
 MCParticles.generatorStatus = 13, 1, 13
[...]
 MCParticles.vertex.x = 0, 0, 30
 MCParticles.vertex.y = 0, 0, 0
 MCParticles.vertex.z = 0, 0, 100
[...]
```

 - Input: see above. Quicker to just copy paste
 - Output: I'll be happy to update if you really want the full thing. There's a lot of cmake and geant happening...
 - Goal: A short description of what you are trying to achieve
Both out-going particles, but especially the final one that I actually care about, should start from the vertex. I.e.
```
 MCParticles.vertex.x = 0, 30, 30
 MCParticles.vertex.y = 0, 0, 0
 MCParticles.vertex.z = 0, 100, 100
```

Notes:
- This is the shortest demo. I've also constructed more complete examples with proper beam (status 4) particles to no effect.
- I've chased it down further into Geant4InputHandling.cpp, Geant4InputAction.cpp, it gets increasingly difficult for me to figure out what's wrong.
- I've done some work in the tedium that is reading HepMC in a different package, including displaced vertices and pre-assigned decays
https://github.com/eic/east/blob/main/PrimGenInterface/src/eASTHepMC3Interface.cc
I'll be happy to help if you point me in the right direction

### PR DESCRIPTION
**Pull request by kkauder**
BEGINRELEASENOTES
- Final state HepMC particles were all attached to (0,0,0). Fixed by switching vertex creation for parentless particles to using their end-point instead, fixes #1013
ENDRELEASENOTES

### CODE REVIEW

File: DDG4/include/DDG4/Geant4Particle.h [hunk 1]
```diff
@@ -273,13 +273,13 @@ namespace dd4hep {
...
 
-    /// Access patricle momentum, energy as 4 vector
+    /// Access start vertex as 3-vector
     inline ROOT::Math::Cartesian3D<double> Geant4ParticleHandle::startVertex() const {
       const Geant4Particle* p = particle;
       return ROOT::Math::Cartesian3D<double>(p->vsx,p->vsy,p->vsz);
     }
 
-    /// Access patricle momentum, energy as 4 vector
+    /// Access end start vertex as 3-vector
```
Comment (wdconinc) [inline DDG4/include/DDG4/Geant4Particle.h:282]: Remove `start`.

File: DDG4/hepmc/HepMC3EventReader.cpp [hunk 2]
```diff
@@ -130,12 +130,24 @@ HEPMC3EventReader::readParticles(int event_number, Vertices& vertices, Particles
     p->genStatus = genStatus&G4PARTICLE_GEN_STATUS_MASK;
 
     if ( p->parents.size() == 0 )  {
+      // This is a bit unintuitive. A particle without a parent in HepMC
+      // can only be (something like) a beam particle, and it is attached
+      // to the root vertex, by default (0,0,0) and equal for all parent-less particles.
+      // Therefore, p->vsx etc. is not suitable to cover situations with multiple
+      // particles coming from different vertices.
+      // Intuitively, one should add vertices for all particles that have a parent,
```
Comment (andresailer) [inline DDG4/hepmc/HepMC3EventReader.cpp:138]: If you want your pre-assigned decays to be consistent, you cannot add G4Vertices for each particle that has a parent.

File: DDG4/hepmc/HepMC3EventReader.cpp [hunk 3]
```diff
@@ -130,12 +130,24 @@ HEPMC3EventReader::readParticles(int event_number, Vertices& vertices, Particles
...
+      // but heritage is handled differently in other places so the
+      // fix is to use these parentless particles' end vertices.
+      // Note that for a particle without end vertex (such as in a particle gun),
+      // it defaults to (0,0,0). This cannot be fixed, the information simply isn't in the HepMC file
+      // Having a parent enforces a vertex, having none forbids one.
```
Comment (andresailer) [inline DDG4/hepmc/HepMC3EventReader.cpp:143]: I don't understand where this phrase fits in?

File: DDG4/hepmc/HepMC3EventReader.cpp [hunk 4]
```diff
@@ -130,12 +130,24 @@ HEPMC3EventReader::readParticles(int event_number, Vertices& vertices, Particles
...
+      // This is a bit unintuitive. A particle without a parent in HepMC
+      // can only be (something like) a beam particle, and it is attached
+      // to the root vertex, by default (0,0,0) and equal for all parent-less particles.
+      // Therefore, p->vsx etc. is not suitable to cover situations with multiple
+      // particles coming from different vertices.
+      // Intuitively, one should add vertices for all particles that have a parent,
+      // but heritage is handled differently in other places so the
+      // fix is to use these parentless particles' end vertices.
+      // Note that for a particle without end vertex (such as in a particle gun),
+      // it defaults to (0,0,0). This cannot be fixed, the information simply isn't in the HepMC file
```
Comment (andresailer) [inline DDG4/hepmc/HepMC3EventReader.cpp:142]:
```suggestion
      // it defaults to (0,0,0). This is not an issue, because the information simply isn't in the HepMC file
```

File: DDG4/hepmc/HepMC3EventReader.cpp (hunk 3 above)
Comment (kkauder) [reply DDG4/hepmc/HepMC3EventReader.cpp:143]: Since we're using end vertices, I looked at particles that don't have one and found the handle class defaults to 0. I played around trying to fix that but then realized there's nothing to save, the vertex information is simply gone. By all means shorten, change, clarify the comment, I just wrote what was going through my mind.

**Comment by kkauder** [comment]
What's up with the one random failing test, is that just a fluke?

**Comment by andresailer** [comment]
Yes, has to be a random fluke/timeout.

I'll try to come up with something about the comment.

I also wanted to test with https://github.com/AIDASoft/DD4hep/blob/master/DDTest/inputFiles/g4pythia.hepmc (hepmc 2 ascii?)

**Comment by kkauder** [comment]
In my experience, if you use deduce_reader (since HepMC 3.2.4 or 5 but it's just a header that can be pulled in), the input format is very transparently detected and handled, but better safe than sorry

**Comment by kkauder** [comment]
Anything that needs to be changed for approval?

**Comment by kkauder** [comment]
Cab we merge?

**Comment by andresailer** [comment]
Sorry for the delay, merging now
